server:
  port: 8083

spring:
  application:
    name: helloclient
eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:10000/eureka/
    enabled: false

feign:
  hystrix:
    enabled: false


hystrix:
  command:
    default:
      execution:
        isolation:
          thread :
            timeoutInMilliseconds: 100

##脱离eureka来完成服务调用
helloclient:
  ribbon:
    listOfServers: 127.0.0.1:8001
    NFLoadBalancerRuleClassName: com.ribbon.controller.CustomerRule