###定义实例名
spring:
  application:
    name: helloclient
server:
  port: 8001

##禁止向eureka注册
eureka:
  client:
    enabled: false

logging:
  config: classpath:logback-spring.xml
  path: D:/logs

##脱离eureka来完成服务调用
helloclient:
  ribbon:
    listOfServers: 127.0.0.1:8001
    NFLoadBalancerRuleClassName: com.ribbon.controller.CustomerRule