###定义实例名
spring:
  application:
    name: spring-cloud-ribbon
server:
  port: 8001

##禁止向eureka注册
eureka:
  client:
    enabled: false

logging:
  config: classpath:logback-spring.xml
  path: D:/logs

##脱离eureka来完成服务调用
helloclient:
  ribbon:
    listOfServers: localhost:8001,localhost:8002